# -*- coding: utf-8 -*-
"""telecom.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R7n97OO6ilPV0UPxAA749Xl0xBkw3LFn
"""

!pip install seaborn
!pip install pandas
import seaborn as sns
import pandas as pd
from scipy import stats

df = pd.read_csv("/content/Orange_Telecom_Churn_Data.csv")
pd.set_option("display.max_rows",None)

df.info()

df.select_dtypes(include = "object").columns

df["intl_plan"] = df["intl_plan"].replace({"yes":1,"no":0}).astype(int)

df["intl_plan"].unique()

df["voice_mail_plan"].unique()

df["voice_mail_plan"] = df["voice_mail_plan"].replace({"yes":1,"no":0}).astype(int)

df["voice_mail_plan"].unique()

df["phone_number"].unique()

df["phone_number"] = df["phone_number"].str.replace("-", "", regex=True)

df["phone_number"] = df["phone_number"].astype(int)

df["phone_number"].unique()

df["state"].unique()

from sklearn.preprocessing import OrdinalEncoder
O = OrdinalEncoder()

df["state"] = O.fit_transform(df[["state"]])

df["state"].unique()

df.info()

df["churned"].unique()

df["churned"] = df["churned"].replace({"False":0,"True":1}).astype(int)

df["churned"].unique()

df.info()

df.corr()